Applicationurl=https://www.saucedemo.com/
browser=chrome
Username=standard_user
lockedUsername=locked_out_user
Problemusername=problem_user
glitchusername=performance_glitch_user
errorusername=error_user
visualusername=visual_user
Password=secret_sauce